from lispy.objects.modules_def.standard import *
from lispy.objects.modules_def.random import *
from lispy.objects.modules_def.list import *
from lispy.objects.modules_def.math import *
from lispy.objects.modules_def.statistics import *
from lispy.objects.modules_def.string import *
from lispy.objects.modules_def.file import *
from lispy.objects.modules_def.turtle import *
from lispy.objects.modules_def.sqlite import *
from lispy.objects.modules_def.dict import *
from lispy.objects.modules_def.sys import *
from lispy.objects.modules_def.os import *