from libraries_src.lpygame_src.components.position_component import PositionComponent
from libraries_src.lpygame_src.components.show_component import ShowComponent
from libraries_src.lpygame_src.components.text_component import TextComponent
from libraries_src.lpygame_src.components.sprite_component import SpriteComponent